[project]
name = "finetuning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bitsandbytes>=0.50.2",
    "datasets>=5.0.1",
    "huggingface-hub>=1.33.0",
    "jupyter>=1.1.1",
    "peft>=0.21.2",
    "transformers>=5.18.0",
    "trl>=1.14.1",
]
